name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
    branches: [main]
  pull_request:
    paths-ignore:
      - "docs/**"
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.4

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run Tests
        run: poetry run make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python-version }}
